# Generated by Django 4.2.3 on 2023-08-22 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="product",
            new_name="products",
        ),
    ]
