# Generated by Django 4.2.3 on 2023-08-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "enquiry_type",
                    models.CharField(
                        choices=[
                            ("General Enquiry", "General Enquiry"),
                            ("Customer Service", "Customer Service"),
                            ("Product Support", "Product Support"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("replied", models.BooleanField(default=False)),
            ],
        ),
    ]
