# Generated by Django 4.2.3 on 2023-08-15 21:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_rename_original_bag_order_original_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
