# Generated by Django 4.2.3 on 2023-08-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="has_size",
            field=models.BooleanField(
                blank=True, default=False, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
